# Auto-generated by Tool Builder
from fastapi import APIRouter, Request, Depends
from fastapi.templating import Jinja2Templates
from jinja2 import FileSystemLoader, ChoiceLoader
from pathlib import Path
from app.auth.utils import get_current_user_optional
from app.database import get_db

router = APIRouter()

# Resolve template directories: custom tool first, then main app fallback
_custom_templates_dir = str(Path(__file__).parent / "app/templates")
_main_templates_dir = str(Path(__file__).resolve().parent.parent.parent / "app" / "templates")

templates = Jinja2Templates(directory=_main_templates_dir)
templates.env.loader = ChoiceLoader([
    FileSystemLoader(_custom_templates_dir),
    FileSystemLoader(_main_templates_dir),
])


@router.get("")
async def tool_page(request: Request, db=Depends(get_db)):
    user = await get_current_user_optional(request, None, db)
    if not user:
        from fastapi.responses import RedirectResponse
        return RedirectResponse(url="/auth/login")
    return templates.TemplateResponse("dashboard/index.html", {"request": request, "user": user})
